const MOCKED_MONSTER_DB = [
  { id: 1, name: "Rathalos", type: "Wyverne volante" },
  { id: 2, name: "Glavenus", type: "Wyverne de terre" },
  { id: 3, name: "Lagiacrus", type: "Léviathan" },
  { id: 4, name: "Tzizi-Ya-Ku", type: "Wyverne rapace" },
  { id: 5, name: "Kulu-Ya-Ku", type: "Wyverne rapace" },
  { id: 6, name: "Nargacuga", type: "Wyverne volante" },
  { id: 7, name: "Rathian", type: "Wyverne volante" },
  { id: 8, name: "Zinogre", type: "Wyverne à crocs" },
  { id: 9, name: "Arzuros", type: "Bête à crocs" },
  { id: 10, name: "Grand Jaggi", type: "Wyverne rapace" },
  { id: 11, name: "Mizutsune", type: "Léviathan" },
  { id: 12, name: "Astalos", type: "Wyverne volante" },
  { id: 13, name: "Gammoth", type: "Bête à crocs" },
  { id: 14, name: "Xu Wu", type: "Céphalopode" },
  { id: 15, name: "Tobi-Kadachi", type: "Wyverne à crocs" },
  { id: 16, name: "Lagiacrus abyssal", type: "Léviathan" },
  { id: 17, name: "Glavenus acide", type: "Wyverne de terre" },
  { id: 18, name: "Ajarakan", type: "Bête à crocs" },
  { id: 19, name: "Magnamalo", type: "Wyverne à crocs" },
  { id: 20, name: "Gore Magala", type: "Semi ancien" },
  { id: 21, name: "Shagaru Magala", type: "Dragon ancien" },
  { id: 22, name: "Fatalis", type: "Dragon ancien" },
  { id: 23, name: "Alatreon", type: "Dragon ancien" },
  { id: 24, name: "Dire Miralis", type: "Dragon ancien" },
  { id: 25, name: "Ceadeus", type: "Dragon ancien" },
  { id: 26, name: "Tetsucabra", type: "Amphibien" },
  { id: 27, name: "Zamtrios", type: "Amphibien" },
  { id: 28, name: "Malfestio", type: "Wyverne volante" },
  { id: 29, name: "Hermitaur Damyo", type: "Carapaceon" },
  { id: 30, name: "Cenataur Shogun", type: "Carapaceon" },
  { id: 31, name: "Lala Barina", type: "Temnoceran" },
  { id: 32, name: "Nercylla", type: "Temnoceran" },
  { id: 33, name: "Diablos", type: "Wyverne volante" },
  { id: 34, name: "Monoblos", type: "Wyverne volante" },
];

module.exports = MOCKED_MONSTER_DB;
