openapi: 3.0.3
info:
  title: API Monster Hunter
  description: API Monster Hunter
  version: 1.0.0
  contact:
    name: Support API
    email: support@example.com

servers:
  - url: http://localhost:3000/api/v1
    description: Serveur de développement v1

paths:
  /monsters:
    get:
      summary: "[v1] Récupérer la liste des monstres paginée"
      description: Retourne une liste paginée de tous les monstres disponibles
      parameters:
        - name: page
          in: query
          description: Numéro de page (défaut 1)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Nombre d'éléments par page (défaut 10)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Liste des monstres récupérée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMonstersWithLinks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: "[v1] Créer un nouveau monstre"
      description: Ajoute un nouveau monstre à la bibliothèque (authentification requise)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonsterInput'
      responses:
        '201':
          description: Monstre créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonsterWithLinks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /monsters/{id}:
    get:
      summary: "[v1] Récupérer un monstre par son ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Monstre trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonsterWithLinks'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: "[v1] Mettre à jour un monstre"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonsterInput'
      responses:
        '200':
          description: Monstre mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonsterWithLinks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: "[v1] Supprimer un monstre"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Monstre supprimé avec succès
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /users:
    post:
      summary: "[v1] Créer un nouvel utilisateur"
      description: Ajoute un nouvel utilisateur à la base de données
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithLinks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /users/{id}:
    get:
      summary: "[v1] Récupérer un utilisateur par ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Utilisateur trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithLinks'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /login:
    post:
      summary: "[v1] Authentification utilisateur"
      description: Authentifie un utilisateur et retourne ses données
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/UserWithLinks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    Monster:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Rathalos"
        type:
          type: string
          example: "Wyverne volante"

    MonsterInput:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          type: string

    MonsterWithLinks:
      allOf:
        - $ref: '#/components/schemas/Monster'
        - type: object
          properties:
            _links:
              $ref: '#/components/schemas/HateoasLinks'

    PaginatedMonstersWithLinks:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        totalMonsters:
          type: integer
        totalPages:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/MonsterWithLinks'
        _links:
          $ref: '#/components/schemas/HateoasLinks'

    User:
      type: object
      required:
        - id
        - username
        - password
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "NouvelUser"
        password:
          type: string
          example: "MotDePasse123"

    UserInput:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    UserWithLinks:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            _links:
              type: object
              properties:
                self:
                  type: string
                  format: uri
                  example: "http://localhost:3000/api/v1/users/1"
                collection:
                  type: string
                  format: uri
                  example: "http://localhost:3000/api/v1/users"

    HateoasLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Link'
        collection:
          $ref: '#/components/schemas/Link'
        update:
          $ref: '#/components/schemas/Link'
        delete:
          $ref: '#/components/schemas/Link'
        first:
          $ref: '#/components/schemas/Link'
        last:
          $ref: '#/components/schemas/Link'
        prev:
          $ref: '#/components/schemas/Link'
        next:
          $ref: '#/components/schemas/Link'
        create:
          $ref: '#/components/schemas/Link'

    Link:
      type: object
      properties:
        href:
          type: string
          format: uri
        method:
          type: string
          enum: [GET, POST, PUT, DELETE]
        description:
          type: string

    Error:
      type: object
      properties:
        message:
          type: string
        error:
          type: string

  responses:
    BadRequest:
      description: Requête invalide
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Authentification requise
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Ressource non trouvée
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    InternalServerError:
      description: Erreur serveur interne
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
