openapi: 3.0.3
info:
  title: API Monster Hunter
  description: API Monster Hunter
  version: 1.0.0
  contact:
    name: Support API
    email: support@example.com

servers:
  - url: http://localhost:3000/api/v1
    description: Serveur de développement v1

paths:
  /monsters:
    get:
      summary: "[v1] Récupérer la liste des monstres paginée"
      description: Retourne une liste paginée de tous les monstres disponibles
      parameters:
        - name: page
          in: query
          description: Numéro de page (défaut 1)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Nombre d'éléments par page (défaut 10)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Liste des monstres récupérée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMonstersWithLinks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: "[v1] Créer un nouveau monstre"
      description: Ajoute un nouveau monstre à la bibliothèque (authentification requise)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonsterInput'
            examples:
              example1:
                summary: Exemple de création de monstre
                value:
                  name: "Nargacuga"
                  type: "Wyverne volante"
      responses:
        '201':
          description: monstre créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonsterWithLinks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /monsters/{id}:
    get:
      summary: "[v1] Récupérer un monstre par son ID"
      description: Retourne les détails d'un monstre spécifique
      parameters:
        - name: id
          in: path
          required: true
          description: ID du monstre
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: monstre trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonsterWithLinks'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: "[v1] Mettre à jour un monstre"
      description: Met à jour les informations d'un monstre existant (authentification requise)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID du monstre à mettre à jour
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonsterInput'
            examples:
              example1:
                summary: Exemple de mise à jour
                value:
                  name: "Rathalos"
                  type: "Wyverne volante"
      responses:
        '200':
          description: monstre mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonsterWithLinks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: "[v1] Supprimer un monstre"
      description: Supprime un monstre de la bibliothèque (authentification requise)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID du monstre à supprimer
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: monstre supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "monstre supprimé avec succès"
                  deleted:
                    $ref: '#/components/schemas/MonsterWithLinks'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Monster:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          type: integer
          description: Identifiant unique du monstre
          example: 1
        name:
          type: string
          description: Nom du monstre
          example: "Rathalos"
        type:
          type: string
          description: Type du monstre
          example: "Wyverne volante"

    MonsterInput:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          description: Nom du monstre
          example: "Nargacuga"
          minLength: 1
          maxLength: 255
        type:
          type: string
          description: Type du monstre
          example: "Wyverne volante"
          minLength: 1
          maxLength: 255

    PaginatedMonsters:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 10
        totalItems:
          type: integer
          example: 34
        totalPages:
          type: integer
          example: 4
        data:
          type: array
          items:
            $ref: '#/components/schemas/Monster'

    HateoasLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Link'
        collection:
          $ref: '#/components/schemas/Link'
        update:
          $ref: '#/components/schemas/Link'
        delete:
          $ref: '#/components/schemas/Link'
        first:
          $ref: '#/components/schemas/Link'
        last:
          $ref: '#/components/schemas/Link'
        prev:
          $ref: '#/components/schemas/Link'
        next:
          $ref: '#/components/schemas/Link'
        create:
          $ref: '#/components/schemas/Link'

    Link:
      type: object
      properties:
        href:
          type: string
          format: uri
          example: "http://localhost:3000/api/v1/monsters/1"
        method:
          type: string
          enum: [GET, POST, PUT, DELETE]
          example: "GET"
        description:
          type: string
          example: "Obtenir ce monstre"

    MonsterWithLinks:
      allOf:
        - $ref: '#/components/schemas/Monster'
        - type: object
          properties:
            _links:
              $ref: '#/components/schemas/HateoasLinks'

    PaginatedMonstersWithLinks:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 10
        totalItems:
          type: integer
          example: 34
        totalPages:
          type: integer
          example: 4
        data:
          type: array
          items:
            $ref: '#/components/schemas/MonsterWithLinks'
        _links:
          $ref: '#/components/schemas/HateoasLinks'

    Error:
      type: object
      properties:
        message:
          type: string
          description: Message d'erreur
        error:
          type: string
          description: Détail technique de l'erreur (optionnel)

  responses:
    BadRequest:
      description: Requête invalide
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "name et type sont requis."

    Unauthorized:
      description: Authentification requise
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Token d'authentification manquant"

    Forbidden:
      description: Permissions insuffisantes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Accès refusé. Droits administrateur requis."

    NotFound:
      description: Ressource non trouvée
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "monstre non trouvé"

    InternalServerError:
      description: Erreur interne du serveur
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Erreur serveur interne"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token obtenu après authentification.
        Format: "Bearer {token}"

security:
  - bearerAuth: []
